"""empty message

Revision ID: 29288ffcebc4
Revises: 830fe29ed1d1
Create Date: 2025-01-04 18:12:52.673105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29288ffcebc4'
down_revision = '830fe29ed1d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('film',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.Column('episode_id', sa.Integer(), nullable=False),
    sa.Column('director', sa.String(length=80), nullable=False),
    sa.Column('producer', sa.String(length=200), nullable=False),
    sa.Column('release_date', sa.String(length=80), nullable=False),
    sa.Column('opening_crawl', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('species',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('classification', sa.String(length=80), nullable=False),
    sa.Column('designation', sa.String(length=80), nullable=False),
    sa.Column('average_height', sa.String(length=80), nullable=False),
    sa.Column('average_lifespan', sa.String(length=80), nullable=False),
    sa.Column('eye_colors', sa.String(length=200), nullable=False),
    sa.Column('hair_colors', sa.String(length=200), nullable=False),
    sa.Column('skin_colors', sa.String(length=200), nullable=False),
    sa.Column('language', sa.String(length=80), nullable=False),
    sa.Column('homeworld', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('species')
    op.drop_table('film')
    # ### end Alembic commands ###
